### ISSUE TITLE
Horz Support

### ISSUE THREAD

**Issue by amcdnl** [jkuri/ngSlimscroll#1]
Does it support horzitonal scrolling?  If so, does it support both directions?

**Comment by jkuri** [comment]
Hi, 

It does not support horizontal scrolling (yet), but it's a good idea. I will implement horizontal scroll during the next weekend and notify you here when it will be done.

**Comment by amcdnl** [comment]
:) ...

**Comment by mastermind1981** [comment]
:+1:

**Comment by jkuri** [comment]
It now supports horizontal scrolling. See the [demo](http://demo.jankuri.com/ngSlimscroll) for more information.

**Comment by amcdnl** [comment]
@jkuri what about using them both at the same time?

**Comment by jkuri** [comment]
Using vertical and horizontal scroll simultaneously in this directive is currently not possible, but it can be tweaked to achieve this functionality. Pull requests are welcome.

**Comment by mastermind1981** [comment]
:+1:
