### ISSUE TITLE
you can not set height to 100%

### ISSUE THREAD

**Issue by matthiassnellings** [jkuri/ngSlimscroll#12]
I want to have a scrollbar over the entire length of the screen in my left panel. So I want to set the css height of the scrollbar to 100% this does not work because height expects a number and the code adds + 'px'.
I'm using an adapted version which just does:
element.css({
                'overflow': 'hidden',
                'width': scope.width,
                'height': scope.height,
            });

```
        var wrapper = angular.element('<div></div>');
        wrapper.css({
            'position': 'relative',
            'overflow': 'hidden',
            'width': scope.width,
            'height': scope.height
        });
```

I think this is a more generic solution because this allows also input like auto (adapt to the height of your children) and 100% (adapt to the height of your parent)...

**Comment by jkuri** [comment]
Is this tested? If I remember correctly this not worked for me.. if it's working for your please provide PR.
