### ISSUE TITLE
Node Package Manager 

### ISSUE THREAD

**Issue by wendellmva** [jkuri/ngSlimscroll#3]
Hi, could you please release this as a node package. I am using browserify to require all my angular modules and it works great but it would help even more if you could release this as a npm package so I wont have to do all kind of trickery to make browserify accept the bower package thanks!

**Comment by jkuri** [comment]
Sure. Please wait till tomorrow when I'll have time.

**Comment by jkuri** [comment]
Package released as a node package at [https://www.npmjs.com/package/ng-slimscroll](https://www.npmjs.com/package/ng-slimscroll). Please inform me if everything is working fine as this is my first node package. Thanks.

**Comment by wendellmva** [comment]
Thanks, I'll give it a try. I will let you know later today!
