### ISSUE TITLE
Doesn't work on mobile

### ISSUE THREAD

**Issue by mladenplavsic** [jkuri/ngSlimscroll#4]
I have tested a demo page demo.jankuri.com/ngSlimscroll/ using Chrome, Opera and Firefox for Android.

**Comment by jkuri** [comment]
Thanks for noticing. Will fix this during the weekend and leave a comment under this issue when it will be done.

**Comment by jkuri** [comment]
Hi, 

It now works on mobile, tested in Chrome and Safari on iPhone. Please report how it works on Android.
Note that there is new attribute touch-scroll-step, decrease this value if you want to scroll faster on mobile and increase if you want to scroll slower. The default value of this attribute is 200.

Pozdrav.
